### ISSUE TITLE
Replace Disqus for lib.reviews

### ISSUE THREAD

**Issue by nicolasmaia** [SnaKKo/Fossdroid-Core#1]
This is a big ask and likely some time away from being possible, but note that F-Droid is moving towards using https://lib.reviews/ for app reviewing (and possibly commenting too); see more at: https://gitlab.com/fdroid/fdroidclient/issues/646

This ticket is mostly intended as a reminder of this ongoing process, and that it should be embedded into Fossdroid when the time comes.

**Comment by ghost** [comment]
It would also be nice if fossdroid and f-droid shared comments, so fossdroid showed the comments made on f-droid and allowed users to add to them.

**Comment by SnaKKo** [comment]
Hi guys, this repo is for Fossdroid Core (not for fossdroid.com).
I will take your advice, thanks.

**Comment by nicolasmaia** [comment]
While not strictly the same thing, wouldn't it be helpful to keep fossdroid.com issues on this repo too? Feels easier than email for feature requests/bugs/general feedback/etc

**Comment by SnaKKo** [comment]
Because they are two different things: it's the same difference between Wordpress CMS and any other blog that uses it.
What I can do is implement a form in fossdroid.com to collect suggestions, feedback, ect...
