### ISSUE TITLE
Error installing Symfony using Composer 1.3.x

### ISSUE THREAD

**Issue by tsoltanovv** [SnaKKo/Fossdroid-Core#4]
After ınstall. Please help
Fatal error: Uncaught Twig_Error_Loader: The "/customers/4/3/3/tsoltanov.com/httpd.www/apps\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle/Resources/views" directory does not exist ("/customers/4/3/3/tsoltanov.com/httpd.www/apps\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle/Resources/views"). in /customers/4/3/3/tsoltanov.com/httpd.www/apps/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:101 Stack trace: #0 /customers/4/3/3/tsoltanov.com/httpd.www/apps/app/cache/prod/appProdProjectContainer.php(2873): Twig_Loader_Filesystem->addPath('/customers/4/3/...', 'Framework') #1 /customers/4/3/3/tsoltanov.com/httpd.www/apps/app/bootstrap.php.cache(2226): appProdProjectContainer->getTwig_LoaderService() #2 /customers/4/3/3/tsoltanov.com/httpd.www/apps/app/cache/prod/appProdProjectContainer.php(2798): Symfony\Component\DependencyInjection\Container->get('twig.loader') #3 /customers/4/3/3/tsoltanov.com/httpd.www/apps/app/bootstrap.php.cache(2226): appProdProjectContainer->getTwigService() #4 /customers/4/3/3/ts in /customers/4/3/3/tsoltanov.com/httpd.www/apps/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 101

**Comment by tsoltanovv** [comment]
no fixed (

**Comment by SnaKKo** [comment]
Check requirements:

` php app/check.php`

and try to make a clean install (clone & install).

**Comment by tsoltanovv** [comment]
C:\wamp64\www\Fossdroid-Core-master>php app/check.php

Symfony Requirements Checker
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

> PHP is using the following php.ini file:
  C:\wamp64\bin\php\php7.0.10\php.ini

> Checking Symfony requirements:
  .................................WW......


 [OK]
 Your system is ready to run Symfony projects


Optional recommendations to improve your setup
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 * a PHP accelerator should be installed
   > Install and/or enable a PHP accelerator (highly recommended).

 * realpath_cache_size should be at least 5M in php.ini
   > Setting "realpath_cache_size" to e.g. "5242880" or "5M" in
   > php.ini* may improve performance on Windows significantly in some
   > cases.


Note  The command console could use a different php.ini file
~~~~  than the one used with your web server. To be on the
      safe side, please check the requirements from your web
      server using the web/config.php script.
-------------------------------------
error running;
 Fatal error: Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Catchable Fatal Error: Argument 1 passed to Twig_Filter::__construct() must be an instance of string, string given, called in C:\wamp64\www\Fossdroid-Core-master\app\cache\prod\classes.php on line 3601 and defined' in C:\wamp64\www\Fossdroid-Core-master\app\cache\prod\classes.php on line 3308
( ! ) Symfony\Component\Debug\Exception\ContextErrorException: Catchable Fatal Error: Argument 1 passed to Twig_Filter::__construct() must be an instance of string, string given, called in C:\wamp64\www\Fossdroid-Core-master\app\cache\prod\classes.php on line 3601 and defined in C:\wamp64\www\Fossdroid-Core-master\vendor\twig\twig\lib\Twig\Filter.php on line 35

please help

**Comment by SnaKKo** [comment]
PHP version?

**Comment by tsoltanovv** [comment]
php 5.6.25

**Comment by tsoltanovv** [comment]
working thanks.  How to add my apk

**Comment by SnaKKo** [comment]
https://f-droid.org/wiki/page/Inclusion_How-To
