### ISSUE TITLE
Twig_Filter::__construct() must be an instance of string, string given

### ISSUE THREAD

**Issue by tsoltanovv** [SnaKKo/Fossdroid-Core#5]
Fatal error: Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Catchable Fatal Error: Argument 1 passed to Twig_Filter::__construct() must be an instance of string, string given, called in C:\wamp64\www\droid\app\cache\prod\classes.php on line 3601 and defined' in C:\wamp64\www\droid\app\cache\prod\classes.php on line 3308
( ! ) Symfony\Component\Debug\Exception\ContextErrorException: Catchable Fatal Error: Argument 1 passed to Twig_Filter::__construct() must be an instance of string, string given, called in C:\wamp64\www\droid\app\cache\prod\classes.php on line 3601 and defined in C:\wamp64\www\droid\vendor\twig\twig\lib\Twig\Filter.php on line 35
Call Stack
#	Time	Memory	Function	Location
1	0.2706	10866720	Symfony\Component\Debug\ErrorHandler->handleException( )	...\ErrorHandler.php:0
2	0.2706	10866864	call_user_func:{C:\wamp64\www\droid\vendor\symfony\symfony\src\Symfony\Component\Debug\ErrorHandler.php:602} ( )	...\ErrorHandler.php:602
3	0.2706	10867032	Symfony\Component\HttpKernel\HttpKernel->terminateWithException( )	...\ErrorHandler.php:602
4	0.2706	10867128	Symfony\Component\HttpKernel\HttpKernel->handleException( )	...\bootstrap.php.cache:3227
5	0.2707	10867584	Symfony\Component\EventDispatcher\EventDispatcher->dispatch( )	...\bootstrap.php.cache:3279
6	0.2707	10867488	Symfony\Component\EventDispatcher\EventDispatcher->doDispatch( )	...\classes.php:1779
7	0.2708	10867984	call_user_func:{C:\wamp64\www\droid\app\cache\prod\classes.php:1864} ( )	...\classes.php:1864
8	0.2708	10868024	Symfony\Component\HttpKernel\EventListener\ExceptionListener->onKernelException( )	...\classes.php:1864
9	0.2772	11123864	Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle( )	...\ExceptionListener.php:50
10	0.2773	11124848	Symfony\Component\HttpKernel\HttpKernel->handle( )	...\bootstrap.php.cache:3360
11	0.2774	11126496	Symfony\Component\HttpKernel\HttpKernel->handleRaw( )	...\bootstrap.php.cache:3206
12	0.2794	11127872	call_user_func_array:{C:\wamp64\www\droid\app\bootstrap.php.cache:3247} ( )	...\bootstrap.php.cache:3247
13	0.2794	11128360	Symfony\Bundle\TwigBundle\Controller\ExceptionController->showAction( )	...\bootstrap.php.cache:3247
14	0.2816	11131856	Twig_Environment->render( )	...\ExceptionController.php:72
15	0.2816	11131856	Twig_Environment->loadTemplate( )	...\classes.php:3183
16	0.2823	11132936	Twig_Environment->compileSource( )	...\classes.php:3215
17	0.2823	11132936	Twig_Environment->tokenize( )	...\classes.php:3303
18	0.2823	11133888	Twig_Lexer->__construct( )	...\classes.php:3274
19	0.2824	11137544	Twig_Lexer->getOperatorRegex( )	...\Lexer.php:65
20	0.2824	11137912	Twig_Environment->getUnaryOperators( )	...\Lexer.php:353
21	0.2824	11137912	Twig_ExtensionSet->getUnaryOperators( )	...\classes.php:3467
22	0.2824	11137912	Twig_ExtensionSet->initExtensions( )	...\ExtensionSet.php:388
23	0.2824	11137912	Twig_ExtensionSet->initExtension( )	...\ExtensionSet.php:419
24	0.2824	11137912	Twig_Extension_Core->getFilters( )	...\ExtensionSet.php:429
25	0.2824	11138856	Twig_Filter->__construct( )	...\classes.php:3601
26	0.2824	11139536	Symfony\Component\Debug\ErrorHandler->handleError( )	...\classes.php:35
( ! ) Twig_Error_Syntax: An exception has been thrown during the compilation of a template ("Catchable Fatal Error: Argument 1 passed to Twig_Filter::__construct() must be an instance of string, string given, called in C:\wamp64\www\droid\app\cache\prod\classes.php on line 3601 and defined") in "@Twig/Exception/error.html.twig". in C:\wamp64\www\droid\app\cache\prod\classes.php on line 3308
Call Stack
#	Time	Memory	Function	Location
1	0.2706	10866720	Symfony\Component\Debug\ErrorHandler->handleException( )	...\ErrorHandler.php:0
2	0.2855	11224816	Symfony\Component\Debug\ErrorHandler->handleException( )	...\ErrorHandler.php:608

**Comment by SnaKKo** [comment]
PHP version?

**Comment by tsoltanovv** [comment]
Apache/2.4.23 (Win64) PHP/5.6.25 - Port defined for Apache: 80

**Comment by SnaKKo** [comment]
I have just committed a possible fix, try to make a clean install.

I think you have installed Twig 2.0 on PHP 5.6 so you received this weird error:
> Twig_Filter::__construct() must be an instance of string, string given
