### ISSUE TITLE
Suggestions for logos

### ISSUE THREAD

**Issue by redmusic27** [SnaKKo/Fossdroid-Core#7]
I have seen your website. I think the drawback is only on the logo. What you want me to make a logo proposal for it?

**Comment by SnaKKo** [comment]
Hi redmusic27, thanks for your proposal but this repo is just for Fossdroid Core (not for fossdroid.com).
However I think fossdroid.com doesn't need a logo because it's just a web frontend of F-Droid, it's not a standalone web app.
